### PR TITLE
CART-1713 - Implement point-grouping

### PR DESCRIPTION
**Pull request by frndmg**

### CODE REVIEW

**Comment by MultifokalHirn** [comment]
@frndmg please always add the ticket ID to your PRs yourself, otherwise I have to do it for everyone

**Review by MultifokalHirn — APPROVED** [review]
really hard to review tbh
lgtm I guess?

**Comment by felix1m** [comment]
also hard for me to review the content/behaviour. form looks good generally

**Review by felix1m — APPROVED** [review]

**Comment by ahmedtalbi** [comment]
I would like to test on cvat before approving  it. can you set it up on GPU2 @frndmg ??

**Pull request merged**
